// <auto-generated />
using Gml.Web.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gml.Web.Api.Data.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250326124824_AddVkAccessKey")]
    partial class AddVkAccessKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("Gml.Web.Api.Domains.Settings.Settings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CurseForgeKey")
                        .HasColumnType("TEXT");

                    b.Property<bool>("RegistrationIsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StorageHost")
                        .HasColumnType("TEXT");

                    b.Property<string>("StorageLogin")
                        .HasColumnType("TEXT");

                    b.Property<string>("StoragePassword")
                        .HasColumnType("TEXT");

                    b.Property<int>("StorageType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TextureProtocol")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VkKey")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("Gml.Web.Api.Domains.User.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccessToken")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Login")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
